### ISSUE TITLE
A problem when I try to use it with Jakarta

### ISSUE THREAD

**Issue by zhpetkov** [phip1611/docx4j-search-and-replace-util#15]
Hello!
Could you replace "import javax.xml.bind.JAXBElement;" to "import jakarta.xml.bind.JAXBElement;" in "Docx4JSRUtil.java" because it's not working correctly when I try to use it with Jakarta? I will be happy if you upload a version for Jakarta! Thank you!

**Comment by phip1611** [comment]
Hey! 
I'm not active in Java space anymore. I'm not sure what Jakarta is and what possible complications of such a change would be.

Perhaps, it might be an option to fork the code or just copy&paste it into your project and use jakarta instead of javax. You shouldn't expect much upstream updates, anyway.

Thanks!
